//=================================================================
// Copyright 2018 Advanced Micro Devices, Inc. All rights reserved.
//=================================================================

// XML.
#include <tinyxml2/Include/tinyxml2.h>

// Local.
#include <RadeonGPUAnalyzerCLI/Src/kcUtils.h>


//
// kcXmlWriter class
//
class kcXmlWriter
{
public:
    // Generates the header for RGA CLI version info file and writes it to the file specified by "fileName" argument.
    static bool AddVersionInfoHeader(const std::string& fileName);

    // Writes the given list of supported target GPUs to the version info file specified by the "fileName" argument.
    static bool AddVersionInfoGPUList(RgaMode mode, const std::set<std::string>& targets, const std::string& fileName);

    // Writes the system level version info to the version info file specified by the "fileName" argument.
    static bool AddVersionInfoSystemData(const std::vector<beVkPhysAdapterInfo>& info, const std::string& fileName);

    // Generates the RGA CLI metadata file for ROCM-CL mode that contains the list of output
    // files generated by RGA CLI.
    static bool GenerateClSessionMetadataFile(const std::string& fileName, const rgFileEntryData& kernelData,
                                              const rgCLOutputMetadata& outFiles);

    // Generates the RGA CLI metadata file for Vulkan mode that contains the list of output
    // files generated by RGA CLI.
    static bool GenerateVulkanSessionMetadataFile(const std::string& fileName,
                                                  const std::map<std::string, rgVkOutputMetadata>& outputMD);
};
