//=============================================================================
/// Copyright (c) 2024-2026 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Header for class analyzing binary code objects.
//=============================================================================
#ifndef RGA_RADEONGPUANALYZERCLI_SRC_KC_CLI_BINARY_ANALYSIS_H_
#define RGA_RADEONGPUANALYZERCLI_SRC_KC_CLI_BINARY_ANALYSIS_H_

//C++.
#include <memory>

// Backend.
#include "radeon_gpu_analyzer_backend/be_program_builder_vulkan.h"

// Local.
#include "radeon_gpu_analyzer_cli/kc_cli_commander.h"
#include "radeon_gpu_analyzer_cli/kc_data_types.h"
#include "radeon_gpu_analyzer_cli/kc_utils_binary_parser.h"
#include "radeon_gpu_analyzer_cli/kc_utils_binary_default.h"

// Commander interface for binary code objects.
class KcCliBinaryAnalysis
{
public:
    // Default constructor.
    KcCliBinaryAnalysis() = default;

    // Parameterized construction.
    KcCliBinaryAnalysis(std::string binary_codeobj_file, LoggingCallbackFunction callback)
        : binary_codeobj_file_(binary_codeobj_file)
        , log_callback_(callback)
    {
    }

    // Sets Workflow strategy for binary analysis.
    beKA::beStatus DisassembleCodeObject(const Config& config, std::string& text_disassembly);

    // Analyze disassembled codeobject.
    beKA::beStatus AnalyzeCodeObject(const Config& config, const std::string& text_disassembly);

    // Generates the RGA CLI metadata for Binary Analysis mode that contains the list of output
    // files generated by RGA CLI for that binary.
    bool GenerateSessionMetadataFile(const Config& config) const;

    // Generates the RGA CLI analysis for Binary Analysis mode that contains summary of output
    // files generated by RGA CLI for that binary.
    bool GeneratCompilationSummary(const Config& config, RgaAnalysisSummary::AnalysisResult& result) const;

    // Returns the target asic for the binary code object;
    bool GetTargetDevice(std::string& device);

private:
    // Validate .bin input file.
    beKA::beStatus IsBinaryInputValid(const Config& config) const;

    // Write text disassembly to disk.
    beKA::beStatus WriteRawTextDisassembly(const Config& config, const std::string& text_disassembly);

    // Parse text disassembly to ISA disassembly file(s).
    beKA::beStatus ParseDisassembly(const Config& config, const std::string& text_disassembly) const;

    // Parses text disassembly output and extracts a table with
    // the  kernel name being the key and that shader stage's disassembly the value.
    beKA::beStatus ParseKernels(const std::string& text_disassembly, std::map<std::string, std::string>& shader_to_disassembly, std::string& error_msg) const;

    // Write output file(s) to disk.
    beKA::beStatus WriteOutputFiles(const Config& config, const std::map<std::string, std::string>& kernel_to_disassembly, std::string& error_msg) const;

    // Perform post-processing actions.
    void RunPostProcessingSteps(const Config& config) const;

    // Target GPU extracted from dissassembly.
    std::string target_device_;

    // Path to binary code object on disk.
    std::string binary_codeobj_file_;

    // Path to dissassembly text file on disk.
    std::string text_disassembly_file_;

    // Pointer to call ParseAmdgpudisOutput methods - implementation differs for graphics or compute.
    std::unique_ptr<KcCliBinaryDisassemblyStrategy> disassembly_strategy_ = nullptr;

    // Pointer to call Post Processing methods - implementation differs for graphics or compute.
    std::unique_ptr<KcCliBinaryAnalysisStrategy> analysis_strategy_ = nullptr;

    // Log callback function
    LoggingCallbackFunction log_callback_ = nullptr;
};

#endif  // RGA_RADEONGPUANALYZERCLI_SRC_KC_CLI_BINARY_ANALYSIS_H_
