//=============================================================================
/// Copyright (c) 2020-2026 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Header for xml writer class.
//=============================================================================
#ifndef RGA_RADEONGPUANALYZERCLI_SRC_KC_XML_WRITER_H_
#define RGA_RADEONGPUANALYZERCLI_SRC_KC_XML_WRITER_H_

// XML.
#include "tinyxml2.h"

// Backend
#include "radeon_gpu_analyzer_backend/be_analysis_summary.h"

// Local.
#include "radeon_gpu_analyzer_cli/kc_utils.h"

class KcXmlWriter
{
public:
    // Generates the header for RGA CLI version info file and writes it to the file specified by "fileName" argument.
    static bool AddVersionInfoHeader(const std::string& filename);

    // Writes the given list of supported target GPUs to the version info file specified by the "fileName" argument.
    static bool AddVersionInfoGPUList(beKA::RgaMode mode, const std::set<std::string>& targets, const std::string& filename);

    // Writes the system level version info to the version info file specified by the "fileName" argument.
    static bool AddVersionInfoSystemData(const std::vector<BeVkPhysAdapterInfo>& info, const std::string& filename);

    // Generates the RGA CLI metadata file for OpenCL-Offline mode that contains the list of output
    // files generated by RGA CLI.
    static bool GenerateClSessionMetadataFile(const std::string& filename, const RgFileEntryData& kernel_data, const RgClOutputMetadata& out_files);

    // Generates the RGA CLI metadata file for Vulkan mode that contains the list of output
    // files generated by RGA CLI.
    static bool GenerateVulkanSessionMetadataFile(const std::string& filename, const std::map<std::string, RgVkOutputMetadata>& output_metadata);

    // Generates the RGA CLI metadata file for Binary analysis mode that contains the list of output
    // files generated by RGA CLI.
    static bool GenerateBinaryAnalysisSessionMetadataFile(const std::string&        filename,
                                                          const std::string&        binary_codeobj_file,
                                                          const RgClOutputMetadata& out_files);

    // Write analysis summary to an XML file.
    // Returns true on success, false on failure.
    static bool WriteAnalysisSummaryToFile(const RgaAnalysisSummary& summary, const std::string& filename);

private:
    // Write document metadata element.
    static void WriteDocument(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* root, const RgaAnalysisSummary::Document& document);

    // Write target architecture metadata element.
    static void WriteTargetArchitectureMetadata(tinyxml2::XMLDocument&                                doc,
                                                tinyxml2::XMLElement*                                 parent,
                                                const RgaAnalysisSummary::TargetArchitectureMetadata& metadata);

    // Write metadata types (branch instruction types, register types, functional groups).
    static void WriteMetadataTypes(tinyxml2::XMLDocument&                                                           doc,
                                   tinyxml2::XMLElement*                                                            parent,
                                   const char*                                                                      container_name,
                                   const char*                                                                      element_name,
                                   const char*                                                                      id_name,
                                   const char*                                                                      name_name,
                                   const char*                                                                      description_name,
                                   const std::vector<RgaAnalysisSummary::TargetArchitectureMetadata::MetadataType>& types);

    // Write inputs section.
    static void WriteInputs(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::AnalysisResult::Inputs& inputs);

    // Write output section.
    static void WriteOutput(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::AnalysisResult::Output& output);

    // Write kernel element.
    static void WriteKernel(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::Kernel& kernel);

    // Write ISA section.
    static void WriteISA(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::Kernel& kernel);

    // Write blocks section.
    static void WriteBlocks(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::BasicBlocks& blocks);

    // Write basic block element.
    static void WriteBlock(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::BasicBlock& block);

    // Write block metadata element.
    static void WriteBlockMetadata(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::BasicBlock::Metadata& metadata);

    // Write block instruction references (V4 simplified format).
    static void WriteBlockInstructions(tinyxml2::XMLDocument&                                       doc,
                                       tinyxml2::XMLElement*                                        parent,
                                       const RgaAnalysisSummary::BasicBlock::InstructionReferences& instruction_refs);

    // Write live registers in element.
    static void WriteLiveRegisters(tinyxml2::XMLDocument&                               doc,
                                   tinyxml2::XMLElement*                                parent,
                                   std::string                                          name,
                                   const RgaAnalysisSummary::BasicBlock::LiveRegisters& live_registers);

    // Write instructions section.
    static void WriteInstructions(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::Instructions& instructions);

    // Write instruction element.
    static void WriteInstruction(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::Instruction& instruction);

    // Write instruction semantics element.
    static void WriteInstructionSemantics(tinyxml2::XMLDocument&                            doc,
                                          tinyxml2::XMLElement*                             parent,
                                          const RgaAnalysisSummary::Instruction::Semantics& semantics);

    // Write branch info element.
    static void WriteBranchInfo(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::Instruction::BranchInfo& branch_info);

    // Write instruction debug info element.
    static void WriteInstructionDebugInfo(tinyxml2::XMLDocument&                            doc,
                                          tinyxml2::XMLElement*                             parent,
                                          const RgaAnalysisSummary::Instruction::DebugInfo& debug_info);

    // Write high-level source element.
    static void WriteHighLevelSource(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::Instruction::HighLevelSource& source);

    // Write operands section.
    static void WriteOperands(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::Instruction::Operands& operands);

    // Write operand element.
    static void WriteOperand(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::Instruction::Operand& operand);

    // Write functional group metadata to the target architecture metadata section.
    static void WriteFunctionalGroupMetadata(
        tinyxml2::XMLDocument&                                                                           doc,
        tinyxml2::XMLElement*                                                                            parent,
        const std::vector<RgaAnalysisSummary::TargetArchitectureMetadata::FunctionalGroupMetadata>& groups);

    // Write VGPRs access section.
    static void WriteRegisterAccess(tinyxml2::XMLDocument&                                              doc,
                                    tinyxml2::XMLElement*                                               parent,
                                    beKA::BeIsaSpecExplorer::RegisterType                               reg_type,
                                    const std::vector<RgaAnalysisSummary::Instruction::RegisterAccess>& reg_access);

    // Write VGPR access element.
    static void WriteRegisterAccess(tinyxml2::XMLDocument&                                 doc,
                                    tinyxml2::XMLElement*                                  parent,
                                    beKA::BeIsaSpecExplorer::RegisterType                  reg_type,
                                    const RgaAnalysisSummary::Instruction::RegisterAccess& reg_access);

    // Write CFG (control flow graph) section.
    static void WriteCFG(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const std::vector<RgaAnalysisSummary::ControlFlowGraph::Branch>& branches);

    // Write branch element.
    static void WriteBranch(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::ControlFlowGraph::Branch& branch);

    // Write statistics section.
    static void WriteStatistics(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::Statistics& stats);

    // Write analysis results section.
    static void WriteAnalysisResults(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* root, const std::vector<RgaAnalysisSummary::AnalysisResult>& results);

    // Write analysis result element.
    static void WriteAnalysisResult(tinyxml2::XMLDocument& doc, tinyxml2::XMLElement* parent, const RgaAnalysisSummary::AnalysisResult& result);

    // Create text element with given name and content.
    // Returns nullptr on allocation failure.
    static tinyxml2::XMLElement* CreateTextElement(tinyxml2::XMLDocument& doc, const char* name, const std::string& text);

    // Create integer element with given name and value.
    // Returns nullptr on allocation failure.
    static tinyxml2::XMLElement* CreateIntElement(tinyxml2::XMLDocument& doc, const char* name, int value);

    // Create uint64_t element with given name and value.
    // Returns nullptr on allocation failure.
    static tinyxml2::XMLElement* CreateUInt64Element(tinyxml2::XMLDocument& doc, const char* name, uint64_t value);

    // Create boolean element with given name and value.
    // Returns nullptr on allocation failure.
    static tinyxml2::XMLElement* CreateBoolElement(tinyxml2::XMLDocument& doc, const char* name, bool value);
};

#endif  // RGA_RADEONGPUANALYZERCLI_SRC_KC_XML_WRITER_H_
