//=====================================================================
// Copyright 2017 (c), Advanced Micro Devices, Inc. All rights reserved.
//
// This file is auto-generated by the LC Device Generator utility.
//=====================================================================

#include <vector>

static const std::set<std::string>  LC_TARGET_NAMES = { "gfx900" };
