//=================================================================
// Copyright 2024 Advanced Micro Devices, Inc. All rights reserved.
//=================================================================
#ifndef RGA_RADEONGPUANALYZERBACKEND_SRC_BE_GENERATOR_DX12_H_
#define RGA_RADEONGPUANALYZERBACKEND_SRC_BE_GENERATOR_DX12_H_

// CLI.
#include "source/radeon_gpu_analyzer_cli/kc_config.h"

// Local.
#include "radeon_gpu_analyzer_backend/be_include.h"
#include "radeon_gpu_analyzer_backend/autogen/be_include_dx12.h"
#include "radeon_gpu_analyzer_backend/autogen/be_compiler_dx12.h"

// C++
#include <string>
#include <memory>

class BeDx12AutoGenerator
{
public:
    // Checks if Autogeneration is required/possible.
    // Populates the input data structure with necessary details for autogeneration.
    // returns true, if any part of the graphics pipeline needs to be autogenerated.
    BeDx12AutoGenStatus PopulateAutoGenInputs(const Config& config, BeDx12AutoGenInput& input_files, std::stringstream& err);

    // Rga enhanced - autogenerate missing parts of the Dx12 pipeline.
    beKA::beStatus GenerateFiles(const Config&              config,
                                 const BeDx12AutoGenInput&  src_input,
                                 const std::string&         autogen_dir,
                                 BeDx12AutoGenFile&         root_signature,
                                 BeDx12AutoGenFile&         gpso_file,
                                 BeDx12AutoGenFile&         vertex_shader,
                                 BeDx12AutoGenFile&         pixel_shader,
                                 std::stringstream&         err) const;

private:
    // Creates the root signature file name to be autogenerated from Config.
    static bool GenerateRootSignatureFileName(const std::string& autogen_dir, std::string& filename);

    // Creates the gpso file name to be autogenerated from Config.
    static bool GenerateGpsoFileName(const std::string& autogen_dir, std::string& filename);

    // Creates the vertex shader file name to be autogenerated from Config.
    static bool GenerateVertexShaderFileName(const std::string& autogen_dir, std::string& filename);

    // Creates pixel shader file name to be autogenerated from Config.
    static bool GeneratePixelShaderFileName(const std::string& autogen_dir, std::string& filename);

    // Dxc compiler.
    std::unique_ptr<BeDx12Compiler> compiler_;
};

#endif  // RGA_RADEONGPUANALYZERBACKEND_SRC_BE_GENERATOR_DX12_H_
